# Generated by Django 5.1 on 2024-09-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_remove_user_username_user_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Enter tg chat id', max_length=64, null=True, verbose_name='Telegram chat id'),
        ),
    ]
