# Generated by Django 5.1 on 2024-08-25 15:51

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.TextField(help_text='Укажите место для выполнения привычки', verbose_name='Место для выполнения привычки')),
                ('performance_time', models.TimeField(help_text='Укажите время выполнения привычки', verbose_name='Время выполнения привычки')),
                ('action', models.TextField(help_text='Укажите действие, которое представляет собой привычка', verbose_name='Действие, которое представляет собой привычка')),
                ('is_pleasant', models.BooleanField(blank=True, default=False, help_text='Укажите, является ли привычка приятной', null=True, verbose_name='Флаг приятной привычки')),
                ('frequency', models.DurationField(default=datetime.timedelta(days=1), help_text='Укажите время на выполнение привычки', verbose_name='Время на выполнение привычки')),
                ('is_public', models.BooleanField(blank=True, default=False, help_text='Укажите, является ли привычка публичной', null=True, verbose_name='Флаг публичной привычки')),
                ('associated_habit', models.ForeignKey(blank=True, help_text='Укажите связанную привычку', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='useful_habit', to='habits.habit', verbose_name='Связанная привычка')),
                ('owner', models.ForeignKey(blank=True, help_text='Укажите создателя привычки', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
        ),
    ]
