# Generated by Django 5.1 on 2024-08-27 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'verbose_name': 'Привычка', 'verbose_name_plural': 'Привычки'},
        ),
        migrations.AlterField(
            model_name='habit',
            name='frequency',
            field=models.DurationField(default=datetime.timedelta(days=1), help_text='Укажите периодичность выполнения привычки в днях', verbose_name='Периодичность выполнения привычки в днях'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='performance_time',
            field=models.TimeField(help_text='Укажите время, когда необходимо выполнять привычку', verbose_name='Время, когда необходимо выполнять привычку'),
        ),
    ]
