# Generated by Django 5.1 on 2024-08-27 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_options_alter_habit_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='habit_time',
            field=models.DurationField(default=datetime.timedelta(seconds=60), help_text='Укажите время в минутах, которое предположительно потратит пользователь на выполнение привычки', verbose_name='Время в минутах, которое предположительно потратит пользователь на выполнение привычки'),
        ),
        migrations.AddField(
            model_name='habit',
            name='reward',
            field=models.TextField(blank=True, help_text='Укажите вознаграждение за выполнение привычки', null=True, verbose_name='Вознаграждение за выполнение привычки'),
        ),
    ]
