# Generated by Django 5.1 on 2024-08-27 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_habit_habit_time_habit_reward'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='performance_time',
            new_name='perform_at',
        ),
    ]
